export const unitTypeById = [
  { value: 1, name: 'Примірник' },
  { value: 2, name: 'Штука' },
  { value: 3, name: 'Бочка' },
  { value: 4, name: 'Ампула' },
  { value: 5, name: 'Балон' },
  { value: 6, name: 'Банка' },
  { value: 7, name: 'Каністра' },
  { value: 8, name: 'Контейнер' },
  { value: 9, name: 'Коробка' },
  { value: 10, name: 'Мішок' },
  { value: 11, name: 'Пляшка' },
  { value: 12, name: 'Флакон' },
  { value: 13, name: 'Цистерна' },
  { value: 14, name: 'Ящик' },
  { value: 15, name: 'Бухта' },
  { value: 16, name: 'Паковання' },
  { value: 17, name: 'Пакунок' },
  { value: 18, name: 'Пачка' },
  { value: 19, name: 'Рулон' },
  { value: 20, name: 'Тюбик' },
  { value: 21, name: 'Моток' },
  { value: 22, name: 'Набір' },
  { value: 23, name: 'Виріб' },
  { value: 24, name: 'Комплект' },
  { value: 25, name: 'Порція' },
  { value: 26, name: 'Метр' },
  { value: 27, name: 'Сантиметр' },
  { value: 28, name: 'Міліметр' },
  { value: 29, name: 'Квадтраний метр' },
  { value: 30, name: 'Квадтраний сантиметр' },
  { value: 31, name: 'Кубічний метр' },
  { value: 32, name: 'Літр' },
  { value: 33, name: 'Мілілітр' },
  { value: 34, name: 'Кілограм' },
  { value: 35, name: 'Грам' },
  { value: 36, name: 'Тонна метрична' },
  { value: 37, name: 'Центнер' },
  { value: 38, name: 'Погонний метр пог' },
  { value: 39, name: 'Кілометр' },
  { value: 40, name: 'Хвилина' },
];
